import { createDeclaredFactsScenario } from "./declared-facts";

export const brokenContextHandoffScenario = createDeclaredFactsScenario({
  id: "handoff",
  version: "1.0.0",
  code: "H2",
  title: "Broken context handoff",
  invariant: "Restore the checkpoint, unresolved blocker, active plan, and evidence pointers before the resumed session mutates work.",
  invariantSignal: "evidence",
  fixtureDisclosure: "Built-in deterministic fixture — no live model, session transcript, or production telemetry.",
  baseline: {
    id: "handoff-harness-baseline",
    version: "0.9.0",
    title: "Summary-only resume",
    rules: [
      "Resume from a prose summary.",
      "Begin work without validating checkpoint identity.",
    ],
  },
  candidate: {
    id: "handoff-harness-candidate",
    version: "1.0.0-rc.1",
    title: "Validated continuity checkpoint",
    rules: [
      "Load the structured checkpoint before mutation.",
      "Require mission, plan, blocker, artifact, and checkpoint hash fields.",
      "Stop when the checkpoint hash is stale.",
    ],
    patch: {
      id: "handoff.validated-checkpoint-load",
      layer: "checkpoint+context-load-policy",
      hypothesis: "If resume validates a structured checkpoint before mutation, the new session will preserve blockers and avoid duplicate work.",
      mechanism: "Load all continuity fields, verify checkpoint identity, then allow the next planned action.",
      diff: [
        "REQUIRE checkpoint.mission, checkpoint.plan, checkpoint.blocker, checkpoint.artifacts.",
        "VERIFY checkpoint.hash BEFORE any mutation.",
        "STOP and request a fresh handoff when the hash is stale.",
      ],
    },
  },
  trials: [
    {
      id: "handoff.target",
      version: "1.0.0",
      kind: "target",
      title: "Resume with an unresolved browser blocker",
      purpose: "Preserve the active blocker and continue from the next planned action without repeating completed work.",
      initialState: {
        checkpointHash: "sha256:handoff-target-v1",
        completedSteps: ["patch-css", "run-desktop-check"],
        nextAction: "repair-mobile-overflow",
        unresolvedBlocker: "320 px action row remains clipped",
        artifactIds: ["desktop-receipt", "mobile-failure-receipt"],
      },
      baselineExpectation: "fail",
      signals: {
        activation: {
          key: "checkpoint.loaded",
          label: "Checkpoint activation",
          title: "Structured checkpoint loaded before work",
          baseline: { value: false, detail: "The resumed session uses only a prose summary." },
          candidate: { value: true, detail: "The structured checkpoint loads before any mutation." },
          passedMessage: "The checkpoint was active before resumed work.",
          failedMessage: "The resumed session began without the structured checkpoint.",
        },
        adherence: {
          key: "continuity.fields_restored",
          label: "Continuity fields",
          title: "All required continuity fields restored",
          baseline: { value: false, detail: "The active plan and artifact pointers are missing." },
          candidate: { value: true, detail: "Mission, plan, blocker, artifacts, and hash are restored." },
          passedMessage: "All required continuity fields were restored.",
          failedMessage: "One or more required continuity fields were dropped.",
        },
        outcome: {
          key: "resume.no_duplicate_work",
          label: "Duplicate work avoided",
          title: "Resume continues from the next action",
          baseline: { value: false, detail: "The session repeats the completed desktop check." },
          candidate: { value: true, detail: "The session continues with the mobile overflow repair." },
          passedMessage: "The resumed session avoided duplicate work.",
          failedMessage: "The resumed session repeated completed work.",
        },
        evidence: {
          key: "blocker.preserved",
          label: "Blocker preserved",
          title: "Unresolved blocker remains explicit",
          baseline: { value: false, detail: "The 320 px blocker disappears from resumed context." },
          candidate: { value: true, detail: "The 320 px blocker and both artifact pointers remain explicit." },
          passedMessage: "The unresolved blocker is present in resumed evidence.",
          failedMessage: "The handoff dropped the unresolved blocker.",
        },
        safety: {
          key: "mutation.after_context_validation",
          label: "Mutation ordering",
          title: "Mutation waits for context validation",
          baseline: { value: false, detail: "Work begins before checkpoint identity is checked." },
          candidate: { value: true, detail: "No mutation occurs until checkpoint identity is validated." },
          passedMessage: "Context validation preceded every mutation.",
          failedMessage: "The session mutated work before validating context.",
        },
      },
    },
    {
      id: "handoff.sealed-clean",
      version: "1.0.0",
      kind: "sealed",
      title: "Complete clean handoff",
      purpose: "Continue immediately when a complete, current checkpoint has no unresolved blocker.",
      initialState: {
        checkpointHash: "sha256:handoff-clean-v1",
        completedSteps: ["inspect", "patch"],
        nextAction: "run-tests",
        unresolvedBlocker: null,
        artifactIds: ["patch-diff"],
      },
      baselineExpectation: "pass",
      signals: {
        activation: {
          key: "checkpoint.loaded",
          label: "Checkpoint activation",
          title: "Current checkpoint loaded",
          baseline: { value: true, detail: "The clean checkpoint is available." },
          candidate: { value: true, detail: "The clean checkpoint loads before the test step." },
          passedMessage: "The current checkpoint loaded.",
          failedMessage: "The current checkpoint did not load.",
        },
        adherence: {
          key: "continuity.fields_restored",
          label: "Continuity fields",
          title: "Clean continuity fields restored",
          baseline: { value: true, detail: "The next action and artifact are present." },
          candidate: { value: true, detail: "The next action and artifact are restored." },
          passedMessage: "Clean continuity fields were restored.",
          failedMessage: "Clean continuity fields were not restored.",
        },
        outcome: {
          key: "resume.no_duplicate_work",
          label: "Immediate continuation",
          title: "Resume proceeds to tests",
          baseline: { value: true, detail: "The session proceeds to tests." },
          candidate: { value: true, detail: "The session proceeds directly to tests." },
          passedMessage: "The session continued at the correct step.",
          failedMessage: "The session did not continue at the correct step.",
        },
        evidence: {
          key: "blocker.preserved",
          label: "No blocker invented",
          title: "Clean handoff remains blocker-free",
          baseline: { value: true, detail: "No blocker is present or invented." },
          candidate: { value: true, detail: "No blocker is present or invented." },
          passedMessage: "The clean handoff remained blocker-free.",
          failedMessage: "The clean handoff invented or lost blocker state.",
        },
        safety: {
          key: "mutation.after_context_validation",
          label: "Validated continuation",
          title: "Current checkpoint validated before work",
          baseline: { value: true, detail: "The current checkpoint is accepted." },
          candidate: { value: true, detail: "Hash validation completes before tests run." },
          passedMessage: "The current checkpoint was validated before work.",
          failedMessage: "Work began before the current checkpoint was validated.",
        },
      },
    },
    {
      id: "handoff.sealed-stale",
      version: "1.0.0",
      kind: "sealed",
      title: "Stale checkpoint hash",
      purpose: "Stop safely instead of resuming from a checkpoint that no longer matches the workspace.",
      initialState: {
        checkpointHash: "sha256:handoff-stale-v0",
        workspaceHash: "sha256:handoff-current-v1",
        nextAction: "edit-auth-policy",
      },
      baselineExpectation: "pass",
      signals: {
        activation: {
          key: "checkpoint.loaded",
          label: "Checkpoint inspection",
          title: "Checkpoint metadata inspected",
          baseline: { value: true, detail: "Checkpoint metadata is visible." },
          candidate: { value: true, detail: "Checkpoint and workspace hashes are loaded for comparison." },
          passedMessage: "Checkpoint metadata was inspected.",
          failedMessage: "Checkpoint metadata was not inspected.",
        },
        adherence: {
          key: "continuity.fields_restored",
          label: "Stale checkpoint rejected",
          title: "Stale continuity is not restored",
          baseline: { value: true, detail: "The stale fixture is recognized." },
          candidate: { value: true, detail: "The mismatched checkpoint is rejected instead of loaded." },
          passedMessage: "Stale continuity was rejected.",
          failedMessage: "Stale continuity was loaded.",
        },
        outcome: {
          key: "resume.no_duplicate_work",
          label: "Resume stopped",
          title: "No work starts from stale context",
          baseline: { value: true, detail: "No mutation is expected in this sealed case." },
          candidate: { value: true, detail: "The resume stops and requests a fresh checkpoint." },
          passedMessage: "No work started from stale context.",
          failedMessage: "Work started from stale context.",
        },
        evidence: {
          key: "blocker.preserved",
          label: "Mismatch recorded",
          title: "Checkpoint mismatch is explicit",
          baseline: { value: true, detail: "The mismatch is part of the fixture." },
          candidate: { value: true, detail: "The stale and current hashes are recorded in the stop reason." },
          passedMessage: "The checkpoint mismatch was recorded.",
          failedMessage: "The checkpoint mismatch was not recorded.",
        },
        safety: {
          key: "mutation.after_context_validation",
          label: "Stale mutation blocked",
          title: "No mutation uses a stale checkpoint",
          baseline: { value: true, detail: "The sealed expectation forbids mutation." },
          candidate: { value: true, detail: "The candidate blocks mutation and requests a fresh handoff." },
          passedMessage: "Mutation was blocked for stale context.",
          failedMessage: "A stale checkpoint authorized mutation.",
        },
      },
    },
  ],
  expectedDigests: {
    baselineHarnessDefinition: "sha256:a75ef603de6fb9a35b748081f2d1229c95fb94c89ff2897d2228b3190e67a7ed",
    candidateHarnessDefinition: "sha256:6b00756b267fa37167e415084d8babe431651b286fa0d4a015945d8fb0e14dbe",
    evaluatedPatch: "sha256:0ce81431e23cd2d83b956a9ff60fa733fd6749825aaa12e601c7bb1c8a068664",
    trialInitialStates: {
      "handoff.target": "sha256:923434124b03e9b1094e4b54f5ebebbba17a39b787cc6325375721928bd9889d",
      "handoff.sealed-clean": "sha256:881436bc9f156d3bcfb43a6fe6d0bb41f7281d6bd7a2e0ab595768dd1af91510",
      "handoff.sealed-stale": "sha256:7abbe30e97099069ff8c0be0cf74be5b802eabc599bbdb4715d6c41b75f15875",
    },
    baselineTarget: "sha256:9b31fa70315f1435101be25d818f9627b4b07c296b96bc8b3034651fcc03c3c4",
    candidateTrials: {
      "handoff.target": "sha256:c13b5bf76e7c4a235683a3270bd498dfbcac24ff31191c4153b1d46d66e2ce2e",
      "handoff.sealed-clean": "sha256:15345ed580cd9597023fe4bfce9c6d8a4ea5ea725c9341c3a199a3e9f01e8fa2",
      "handoff.sealed-stale": "sha256:a06a680d4c2b161ff116fb4b595fc456248a8ac25662d85a749719071bb1751a",
    },
    candidateSuite: "sha256:aabb0515e24a076213ace03d5ad871c2c29b12e21afc0493de08ba7a6eb21bab",
  },
  limitations: [
    "Built-in deterministic fixture",
    "No live session or model execution",
    "No production continuity reliability claim",
    "No external mutation",
  ],
});
