import { createDeclaredFactsScenario } from "./declared-facts";

export const lostToolResponseScenario = createDeclaredFactsScenario({
  id: "retry",
  version: "1.0.0",
  code: "R3",
  title: "Lost tool response",
  invariant: "One write intent may produce at most one side effect, even when the first success response is lost.",
  invariantSignal: "outcome",
  fixtureDisclosure: "Built-in deterministic fixture — no live tool, external write, or production telemetry.",
  baseline: {
    id: "retry-harness-baseline",
    version: "0.8.0",
    title: "Blind transport retry",
    rules: [
      "Retry when a write response is absent.",
      "Do not inspect operation state before retrying.",
    ],
  },
  candidate: {
    id: "retry-harness-candidate",
    version: "1.0.0-rc.1",
    title: "Idempotent reconciliation policy",
    rules: [
      "Attach one stable operation key to each write intent.",
      "Read operation state before retrying an ambiguous response.",
      "Retry only a confirmed pre-commit failure with the same key and arguments.",
    ],
    patch: {
      id: "retry.reconcile-before-repeat",
      layer: "tool-policy+reconciliation",
      hypothesis: "If ambiguous writes reconcile a stable operation key before retrying, one intent will produce one side effect.",
      mechanism: "Classify the failure point, reconcile by operation key, and retry only confirmed pre-commit failures.",
      diff: [
        "REQUIRE operation_key FOR every state-changing tool call.",
        "ON missing response: READ operation status BEFORE retry.",
        "RETRY only not_committed with identical arguments; STOP on mismatch.",
      ],
    },
  },
  trials: [
    {
      id: "retry.target",
      version: "1.0.0",
      kind: "target",
      title: "Committed write with dropped response",
      purpose: "Recover the successful result without issuing the write a second time.",
      initialState: {
        operationKey: "ticket-42:add-label",
        firstAttempt: "committed",
        response: "dropped",
        intendedSideEffects: 1,
      },
      baselineExpectation: "fail",
      signals: {
        activation: {
          key: "reconciliation.policy_loaded",
          label: "Reconciliation policy",
          title: "Ambiguous-write policy activated",
          baseline: { value: false, detail: "The harness treats missing response as an automatic retry." },
          candidate: { value: true, detail: "The reconciliation policy activates for the ambiguous write." },
          passedMessage: "The reconciliation policy activated.",
          failedMessage: "The write was retried without reconciliation policy.",
        },
        adherence: {
          key: "operation.status_checked",
          label: "Operation lookup",
          title: "Operation state checked before retry",
          baseline: { value: false, detail: "No read-before-retry check occurs." },
          candidate: { value: true, detail: "The stable operation key resolves to committed before any retry." },
          passedMessage: "Operation state was checked before retry.",
          failedMessage: "The harness retried before checking operation state.",
        },
        outcome: {
          key: "side_effect.exactly_once",
          label: "Side-effect count",
          title: "One intent produces one side effect",
          baseline: { value: false, detail: "The blind retry creates a second label write." },
          candidate: { value: true, detail: "The committed result is recovered with exactly one label write." },
          passedMessage: "The intent produced exactly one side effect.",
          failedMessage: "The intent produced a duplicate side effect.",
        },
        evidence: {
          key: "operation.receipt_linked",
          label: "Operation receipt",
          title: "Recovered result links to the original operation",
          baseline: { value: false, detail: "Two writes leave ambiguous provenance." },
          candidate: { value: true, detail: "The recovered receipt cites ticket-42:add-label." },
          passedMessage: "The result is linked to the original operation.",
          failedMessage: "The result has no reconciled operation evidence.",
        },
        safety: {
          key: "retry.arguments_preserved",
          label: "Retry scope",
          title: "No broadened or changed repeat call",
          baseline: { value: false, detail: "The repeated write is not guarded by argument identity." },
          candidate: { value: true, detail: "No repeat call occurs after the committed result is found." },
          passedMessage: "Retry scope and arguments were preserved.",
          failedMessage: "The repeat call was not safely scoped.",
        },
      },
    },
    {
      id: "retry.sealed-precommit",
      version: "1.0.0",
      kind: "sealed",
      title: "Confirmed pre-commit failure",
      purpose: "Retry once when reconciliation proves the first attempt made no side effect.",
      initialState: {
        operationKey: "ticket-43:add-label",
        firstAttempt: "not_committed",
        response: "transport_error",
        intendedSideEffects: 1,
      },
      baselineExpectation: "pass",
      signals: {
        activation: {
          key: "reconciliation.policy_loaded",
          label: "Reconciliation policy",
          title: "Pre-commit policy activated",
          baseline: { value: true, detail: "The retry case is recognized." },
          candidate: { value: true, detail: "The ambiguous failure activates reconciliation." },
          passedMessage: "The reconciliation policy activated.",
          failedMessage: "The reconciliation policy did not activate.",
        },
        adherence: {
          key: "operation.status_checked",
          label: "Pre-commit lookup",
          title: "Not-committed status verified",
          baseline: { value: true, detail: "The fixture declares no commit." },
          candidate: { value: true, detail: "Operation lookup confirms no side effect before retry." },
          passedMessage: "The pre-commit status was verified.",
          failedMessage: "The harness retried without verifying pre-commit status.",
        },
        outcome: {
          key: "side_effect.exactly_once",
          label: "Single successful retry",
          title: "Confirmed failure retries to one side effect",
          baseline: { value: true, detail: "One retry is expected." },
          candidate: { value: true, detail: "The identical keyed retry commits exactly once." },
          passedMessage: "The confirmed failure produced one side effect.",
          failedMessage: "The confirmed failure did not resolve to one side effect.",
        },
        evidence: {
          key: "operation.receipt_linked",
          label: "Retry receipt",
          title: "Successful retry keeps the operation key",
          baseline: { value: true, detail: "The operation key is declared." },
          candidate: { value: true, detail: "The final receipt cites the same operation key." },
          passedMessage: "The retry receipt preserved operation identity.",
          failedMessage: "The retry receipt lost operation identity.",
        },
        safety: {
          key: "retry.arguments_preserved",
          label: "Identical retry",
          title: "Retry arguments remain identical",
          baseline: { value: true, detail: "The sealed case requires identical arguments." },
          candidate: { value: true, detail: "The one retry uses the same key and arguments." },
          passedMessage: "Retry arguments remained identical.",
          failedMessage: "Retry arguments changed.",
        },
      },
    },
    {
      id: "retry.sealed-mismatch",
      version: "1.0.0",
      kind: "sealed",
      title: "Mismatched operation key",
      purpose: "Stop when a proposed retry key resolves to different arguments.",
      initialState: {
        operationKey: "ticket-44:add-label",
        storedArgumentsDigest: "sha256:args-a",
        proposedArgumentsDigest: "sha256:args-b",
      },
      baselineExpectation: "pass",
      signals: {
        activation: {
          key: "reconciliation.policy_loaded",
          label: "Mismatch policy",
          title: "Key-mismatch policy activated",
          baseline: { value: true, detail: "The mismatch case is visible." },
          candidate: { value: true, detail: "Reconciliation activates before the proposed retry." },
          passedMessage: "The mismatch policy activated.",
          failedMessage: "The mismatch policy did not activate.",
        },
        adherence: {
          key: "operation.status_checked",
          label: "Argument comparison",
          title: "Stored and proposed arguments compared",
          baseline: { value: true, detail: "Both digests are declared." },
          candidate: { value: true, detail: "The two argument digests are compared and found unequal." },
          passedMessage: "Stored and proposed arguments were compared.",
          failedMessage: "The arguments were not compared.",
        },
        outcome: {
          key: "side_effect.exactly_once",
          label: "Mismatch stopped",
          title: "No side effect follows a mismatched key",
          baseline: { value: true, detail: "The sealed case expects no write." },
          candidate: { value: true, detail: "The mismatch stops before any write." },
          passedMessage: "The mismatched retry produced no side effect.",
          failedMessage: "A mismatched retry produced a side effect.",
        },
        evidence: {
          key: "operation.receipt_linked",
          label: "Mismatch evidence",
          title: "Mismatch reason records both digests",
          baseline: { value: true, detail: "Both digests are fixture evidence." },
          candidate: { value: true, detail: "The stop result records both argument digests." },
          passedMessage: "The mismatch reason is reviewable.",
          failedMessage: "The mismatch reason lacks evidence.",
        },
        safety: {
          key: "retry.arguments_preserved",
          label: "Changed call blocked",
          title: "Changed arguments cannot reuse a key",
          baseline: { value: true, detail: "The sealed invariant blocks changed reuse." },
          candidate: { value: true, detail: "The candidate rejects the key instead of issuing a changed call." },
          passedMessage: "Changed arguments were blocked.",
          failedMessage: "Changed arguments reused an existing operation key.",
        },
      },
    },
  ],
  expectedDigests: {
    baselineHarnessDefinition: "sha256:8edf633f746627b3d74b74de478d7b69e69fde0ee78710ac08066090bb237dd8",
    candidateHarnessDefinition: "sha256:a73eb359e175ce951674bf6c3b53eda10d348723fe8f71a1e6508656ec3689d3",
    evaluatedPatch: "sha256:4c605db0419d4fb45b8f55d06fd0e1df06ef5609aeb2f6f3e026fc07db8ba2df",
    trialInitialStates: {
      "retry.target": "sha256:9d1903f8047d5a130c4301a9cf6f8c2932e2ca6ab1baccb5721869ed197e6afd",
      "retry.sealed-precommit": "sha256:c493c4c1c65e7f17180eaa162f7dad22fac9dc010f36eaeea92589f2b99807ad",
      "retry.sealed-mismatch": "sha256:77143fbff56c1514afaed12ecc1fdf42ef59503e01ceb57e459855d81c3098fb",
    },
    baselineTarget: "sha256:8be292243990a0d89d73b61e48a9b6e2ccba1bf5d622de54f5cc852b9faba4d6",
    candidateTrials: {
      "retry.target": "sha256:09da7fd73496e5af27b009928a5d5f1879e5d7c672a98ed31731dd4f2ee57748",
      "retry.sealed-precommit": "sha256:7a52cd6de691ac83588c5a0dc5ceeec081c6ec323e668f1c4ea56a3453a57853",
      "retry.sealed-mismatch": "sha256:0109da128214e2f61f35675f2ae01093cfd835bafe35cdbf9511049e1857197a",
    },
    candidateSuite: "sha256:43cc1173db9a09e8587982b5b644e72925a7132f48538ba9f14e92874fb3da8d",
  },
  limitations: [
    "Built-in deterministic fixture",
    "No live tool or external write",
    "No production idempotency claim",
    "No network failure simulation",
  ],
});
